version: "3.3"
services:
  postgres:
    image: "postgres"
    restart: always
    env_file:
      - configs/postgres.env
  backend:
    build: .
    env_file:
      - configs/backend.env
    ports:
      - "1234:1234"
    depends_on:
      - postgres
    