version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  test_go:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  test:
    jobs:
      - test_go